"""Core demo records shared by every view. ALL DATA IS ILLUSTRATIVE DEMO DATA.
People are 'John Doe' with role labels; brand names are real, vendor names are fictional."""
from .clock import d, dt

USERS = {
    "u_head": {"id": "u_head", "name": "John Doe", "role": "Sourcing head",
               "caps": ["edit", "assign", "reopen", "commercial", "record_decision", "verify_closure", "gate_signoff"]},
    "u_lead": {"id": "u_lead", "name": "John Doe", "role": "Leadership",
               "caps": ["assign", "reopen", "commercial"]},
    "u_merch1": {"id": "u_merch1", "name": "John Doe", "role": "Merchandiser (Argo Navis)",
                 "caps": ["edit", "assign", "record_decision"]},
    "u_merch2": {"id": "u_merch2", "name": "John Doe", "role": "Merchandiser (V-Mart, Jaal)",
                 "caps": ["edit", "assign", "record_decision"]},
    "u_tech": {"id": "u_tech", "name": "John Doe", "role": "Technical reviewer",
               "caps": ["edit", "technical_review"]},
    "u_prod": {"id": "u_prod", "name": "John Doe", "role": "Production coordinator",
               "caps": ["edit", "assign"]},
    "u_qa": {"id": "u_qa", "name": "John Doe", "role": "QA lead",
             "caps": ["edit", "technical_review", "verify_closure", "gate_signoff"]},
}

BRANDS = {
    "b_argo": {"id": "b_argo", "name": "Argo Navis", "owner": "u_head",
               "summary": "AW27 development running in parallel with Meadow shirt production.",
               "contacts": [{"role": "Head of design", "name": "John Doe (brand contact)"},
                            {"role": "Buying manager", "name": "John Doe (brand contact)"}],
               "files": ["AW27 brand brief.pdf", "Fit block reference.pdf"]},
    "b_vmart": {"id": "b_vmart", "name": "V-Mart", "owner": "u_merch2",
                "summary": "Two active tracks: Green ethnic sets and New shirt development.",
                "contacts": [{"role": "Category buyer", "name": "John Doe (brand contact)"}],
                "files": ["Festive range brief.pdf"]},
    "b_jaal": {"id": "b_jaal", "name": "Jaal", "owner": "u_merch2",
               "summary": "Costing complete across 22 styles; price list review scheduled.",
               "contacts": [{"role": "Merchandising lead", "name": "John Doe (brand contact)"}],
               "files": ["Jaal core range list.xlsx"]},
}

# Illustrative source documents. original_url is None: there are no live integrations.
SOURCES = {
    "src_orbit_mtg": {"id": "src_orbit_mtg", "type": "meeting_note", "date": d(-10), "time": "11:00",
        "title": "Argo Navis weekly sync (meeting note excerpt)", "author": "John Doe (Sourcing head)",
        "participants": ["John Doe (Sourcing head)", "John Doe (Technical reviewer)", "John Doe (brand contact)"],
        "excerpt": "Orbit overshirt fit round 2: left sleeve pitch looks 1.5 cm too forward on the received sample. "
                   "Vendor to correct the sleeve pattern and resubmit. Technical review to confirm once the corrected sample arrives. "
                   "Brand wants a decision before the PP slot is locked.",
        "original_url": None, "brand_ids": ["b_argo"], "work_ids": ["w_orbit"], "demo": True},
    "src_orbit_email": {"id": "src_orbit_email", "type": "email", "date": d(-1), "time": "16:20",
        "title": "Re: Orbit overshirt – corrected sleeve sample", "author": "John Doe (vendor contact, Kaveri Apparels)",
        "participants": ["John Doe (vendor contact, Kaveri Apparels)", "John Doe (Merchandiser, Argo Navis)"],
        "excerpt": "We can courier the corrected sample by 9 Oct because the re-dyed fabric lot is only in tomorrow. "
                   "Please confirm if 9 Oct is acceptable.",
        "original_url": None, "brand_ids": ["b_argo"], "work_ids": ["w_orbit"], "demo": True},
    "src_vmart_msg": {"id": "src_vmart_msg", "type": "message", "date": d(-2), "time": "14:05",
        "title": "V-Mart buyer message (summary supplied; original not available)", "author": "John Doe (brand contact)",
        "participants": ["John Doe (brand contact)", "John Doe (Merchandiser, V-Mart)"],
        "excerpt": "Counter-sample for the green ethnic sets was couriered last week. We will confirm receipt and revert on colour by Thursday.",
        "original_url": None, "brand_ids": ["b_vmart"], "work_ids": ["w_green"], "demo": True, "summary_only": True},
    "src_meadow_email": {"id": "src_meadow_email", "type": "email", "date": d(-2), "time": "09:40",
        "title": "Meadow shirt – Vendor B lot 1 inspection", "author": "John Doe (QA lead)",
        "participants": ["John Doe (QA lead)", "John Doe (Production coordinator)"],
        "excerpt": "Final inspection of Lot 1 (Vendor B) failed on collar stitching: 9 major defects against an accept limit recorded in the buyer-approved plan. "
                   "Rework is under way; re-inspection requested for the reworked quantity only.",
        "original_url": None, "brand_ids": ["b_argo"], "work_ids": ["w_meadow"], "demo": True},
    "src_meadow_reply": {"id": "src_meadow_reply", "type": "email", "date": d(0), "time": "08:55",
        "title": "Re: Meadow lot 1 rework status", "author": "John Doe (vendor contact, Lotus Knit Works)",
        "participants": ["John Doe (vendor contact, Lotus Knit Works)", "John Doe (Production coordinator)"],
        "excerpt": "Rework on 410 of 600 collars is complete. The remaining 190 will be done by 8 Oct. Still waiting on the buyer-approved defect limits to be re-confirmed in writing.",
        "original_url": None, "brand_ids": ["b_argo"], "work_ids": ["w_meadow"], "demo": True},
    "src_weekly": {"id": "src_weekly", "type": "meeting_note", "date": d(-3), "time": "10:30",
        "title": "Sourcing weekly review (multi-brand meeting note)", "author": "John Doe (Sourcing head)",
        "participants": ["John Doe (Sourcing head)", "John Doe (Leadership)", "John Doe (Merchandiser, V-Mart, Jaal)"],
        "excerpt": "Full meeting note retained as one record; sections below are linked to the relevant brands.",
        "sections": [
            {"brand_id": "b_argo", "text": "Argo: Orbit round 2 sleeve correction is the main risk. Meadow lot 1 inspection to be scheduled."},
            {"brand_id": "b_vmart", "text": "V-Mart: green sets counter-sample out; New shirt fabric options due next week."},
            {"brand_id": "b_jaal", "text": "Jaal: costing sheets for all 22 styles complete; price list review set for 12 Oct."}],
        "original_url": None, "brand_ids": ["b_argo", "b_vmart", "b_jaal"], "work_ids": [], "demo": True},
    "src_argo_enquiry": {"id": "src_argo_enquiry", "type": "email", "date": d(-4), "time": "12:10",
        "title": "Argo Navis – early enquiry on SS28 resort capsule (not yet linked to any work)",
        "author": "John Doe (brand contact)", "participants": ["John Doe (brand contact)", "John Doe (Sourcing head)"],
        "excerpt": "We are thinking of a small resort capsule for SS28, around 6 styles in linen blends. Can you share which vendors could do resort collars at low minimums?",
        "original_url": None, "brand_ids": ["b_argo"], "work_ids": [], "demo": True, "unlinked": True},
    "src_jaal_note": {"id": "src_jaal_note", "type": "document", "date": d(-5), "time": "17:00",
        "title": "Jaal costing summary (document excerpt)", "author": "John Doe (Merchandiser, V-Mart, Jaal)",
        "participants": [], "excerpt": "Costing sheets completed for all 22 styles on the 'Core range v3' basis. Price list to be reviewed with the brand.",
        "original_url": None, "brand_ids": ["b_jaal"], "work_ids": ["w_jaal"], "demo": True},
}

WORKS = {
    "w_orbit": {"id": "w_orbit", "brand_id": "b_argo", "title": "AW27 Orbit overshirt development", "type": "Sample development",
        "season": "AW27", "owner_id": "u_head", "lifecycle": "active", "stage": "Fit round 2 · correction pending",
        "position": "Fit round 2 sleeve correction outstanding; corrected sample proposed for 9 Oct.",
        "style_ids": ["s_orbit", "s_trail"], "colourway_note": "2 colourways on Orbit", "next_commitment_id": "c_orbit_sample",
        "waiting_on_brand": False, "brief": "Overshirt with workwear detailing; fit block per Argo AW27 reference.",
        "vendor_alloc": [{"vendor_id": "v_kaveri", "scope": "Fit sampling", "style_ids": ["s_orbit"], "historical": False},
                          {"vendor_id": "v_sunrise", "scope": "Competing proto sample", "style_ids": ["s_trail"], "historical": False}],
        "updated_at": dt(-1, "16:30"), "rev": 1},
    "w_green": {"id": "w_green", "brand_id": "b_vmart", "title": "Green ethnic sets", "type": "Collection",
        "season": "Festive", "owner_id": "u_merch2", "lifecycle": "active", "stage": "Counter-sample with brand",
        "position": "Counter-sample sent to V-Mart; waiting on brand colour approval.",
        "style_ids": ["s_gr1", "s_gr2", "s_gr3"], "colourway_note": "2 colourways each", "next_commitment_id": "c_green_insp",
        "waiting_on_brand": True, "brief": "Festive co-ord sets in green family.",
        "vendor_alloc": [{"vendor_id": "v_sunrise", "scope": "Sampling and bulk", "style_ids": ["s_gr1", "s_gr2", "s_gr3"], "historical": False}],
        "updated_at": dt(-2, "14:10"), "rev": 1},
    "w_shirt": {"id": "w_shirt", "brand_id": "b_vmart", "title": "New shirt development", "type": "Development programme",
        "season": "SS27", "owner_id": "u_merch2", "lifecycle": "active", "stage": "Fabric selection",
        "position": "Fabric options being prepared; 3 styles in development, 1 draft missing BOM.",
        "style_ids": ["s_vs1", "s_vs2", "s_vs3"], "colourway_note": "", "next_commitment_id": "c_shirt_fabric",
        "waiting_on_brand": False, "brief": "Core formal and casual shirts.", "vendor_alloc": [],
        "updated_at": dt(-3, "11:00"), "rev": 1},
    "w_jaal": {"id": "w_jaal", "brand_id": "b_jaal", "title": "Core range costing", "type": "Costing programme",
        "season": "SS27", "owner_id": "u_merch2", "lifecycle": "active", "stage": "Costing complete",
        "position": "Costing complete across 22 styles; price list review with brand scheduled.",
        "style_ids": [f"s_jl{n:02d}" for n in range(1, 23)], "colourway_note": "", "next_commitment_id": "c_jaal_review",
        "waiting_on_brand": False, "brief": "Core range costing on 'Core range v3' basis.", "vendor_alloc": [],
        "updated_at": dt(-5, "17:05"), "rev": 1},
    "w_meadow": {"id": "w_meadow", "brand_id": "b_argo", "title": "Meadow shirt AW27 production", "type": "Confirmed order",
        "season": "AW27", "owner_id": "u_head", "lifecycle": "active", "stage": "Parallel production",
        "position": "Vendor A in PP correction (unauthorised cutting start flagged) · Vendor B released and cutting · 1 partial shipment in transit.",
        "style_ids": ["s_meadow"], "colourway_note": "2 colourways · 1,400 pieces ordered", "next_commitment_id": "c_meadow_reinsp",
        "waiting_on_brand": False, "brief": "Confirmed PO PO-AN-2711 split across two vendors.",
        "vendor_alloc": [{"vendor_id": "v_sunrise", "scope": "Bulk production (Vendor A, 700 pcs)", "style_ids": ["s_meadow"], "historical": False},
                          {"vendor_id": "v_lotus", "scope": "Bulk production (Vendor B, 700 pcs)", "style_ids": ["s_meadow"], "historical": False}],
        "updated_at": dt(0, "08:55"), "rev": 1},
}

ISSUES = {
    "i_sleeve": {"id": "i_sleeve", "work_id": "w_orbit", "title": "Sleeve correction unresolved for 10 days",
        "impact": "Fit round 2 cannot be passed internally and the PP slot cannot be locked. Vendor intervention needed to close the correction.",
        "state": "open", "owner_id": "u_tech", "opened_at": dt(-10, "11:30"), "affected_style_ids": ["s_orbit"],
        "action_ids": ["a_tech_review", "a_resubmit"], "source_id": "src_orbit_mtg", "blocking": True, "escalated": False,
        "kind": "Quality / construction", "resolution": None, "rev": 1},
    "i_collar": {"id": "i_collar", "work_id": "w_meadow", "title": "Vendor B Lot 1 failed final inspection (collar stitching)",
        "impact": "Lot 1 cannot be released; remaining Vendor B quantity may miss the dispatch commitment.",
        "state": "open", "owner_id": "u_qa", "opened_at": dt(-2, "09:45"), "affected_style_ids": ["s_meadow"],
        "action_ids": ["a_reinspect", "a_defect_limits"], "source_id": "src_meadow_email", "blocking": True, "escalated": False,
        "kind": "Inspection", "resolution": None, "rev": 1},
    "i_packing": {"id": "i_packing", "work_id": "w_meadow", "title": "Shipment 1 packing list quantity mismatch",
        "impact": "Warehouse receipt may show a variance until the packing list is corrected.",
        "state": "open", "owner_id": "u_prod", "opened_at": dt(-1, "12:00"), "affected_style_ids": ["s_meadow"],
        "action_ids": ["a_packing"], "source_id": None, "blocking": False, "escalated": False,
        "kind": "Fulfilment", "resolution": None, "rev": 1},
    "i_trim": {"id": "i_trim", "work_id": "w_green", "title": "Trim card mismatch on set 2",
        "impact": "Button colour differed from the approved trim card.",
        "state": "resolved", "owner_id": "u_merch2", "opened_at": dt(-9, "10:00"), "affected_style_ids": ["s_gr2"],
        "action_ids": [], "source_id": None, "blocking": False, "escalated": False, "kind": "Material / trim",
        "resolution": {"note": "Vendor replaced buttons; shade matched against approved trim card.", "ref": "Trim card photo (demo)",
                       "by": "u_head", "at": dt(-3, "15:00")}, "rev": 2},
}

ACTIONS = {
    "a_tech_review": {"id": "a_tech_review", "work_id": "w_orbit", "issue_id": "i_sleeve", "title": "Technical review of corrected sleeve sample (fit round 3)",
        "expected_outcome": "Confirm sleeve pitch and armhole measurements are within tolerance on the corrected sample.",
        "assignee_id": "u_tech", "assignment_confirmed": True, "assigned_at": dt(-9, "09:00"), "due": d(-1), "status": "open",
        "blocked": None, "requires_review": False, "style_id": "s_orbit", "vendor_id": "v_kaveri", "sample_round_id": "sr_orbit_3",
        "completion": None, "created_at": dt(-10, "12:00"), "origin": "source", "source_id": "src_orbit_mtg", "rev": 1},
    "a_resubmit": {"id": "a_resubmit", "work_id": "w_orbit", "issue_id": "i_sleeve", "title": "Get corrected sleeve sample from Kaveri Apparels",
        "expected_outcome": "Corrected round 2 sample couriered and receipt confirmed.",
        "assignee_id": "u_merch1", "assignment_confirmed": True, "assigned_at": dt(-10, "12:00"), "due": d(-3), "status": "blocked",
        "blocked": {"needs": "Re-dyed fabric lot and corrected pattern", "from": "Kaveri Apparels (vendor)"},
        "requires_review": False, "style_id": "s_orbit", "vendor_id": "v_kaveri", "sample_round_id": "sr_orbit_3", "completes_on_receipt": True,
        "completion": None, "created_at": dt(-10, "12:00"), "origin": "source", "source_id": "src_orbit_email", "rev": 1},
    "a_confirm_counter": {"id": "a_confirm_counter", "work_id": "w_green", "issue_id": None, "title": "Confirm counter-sample receipt at V-Mart",
        "expected_outcome": "V-Mart confirms receipt of the counter-sample before inspection planning.",
        "assignee_id": "u_merch2", "assignment_confirmed": True, "assigned_at": dt(-4, "10:00"), "due": d(1), "status": "open",
        "blocked": None, "requires_review": False, "style_id": "s_gr1", "vendor_id": None, "sample_round_id": "sr_green1_1", "completes_on_receipt": True,
        "completion": None, "created_at": dt(-4, "10:00"), "origin": "source", "source_id": "src_vmart_msg", "rev": 1},
    "a_fabric_options": {"id": "a_fabric_options", "work_id": "w_shirt", "issue_id": None, "title": "Share fabric options with V-Mart",
        "expected_outcome": "Fabric option deck shared with the category buyer.",
        "assignee_id": "u_merch1", "assignment_confirmed": True, "assigned_at": dt(-5, "10:00"), "due": d(3), "status": "open",
        "blocked": None, "requires_review": False, "style_id": None, "vendor_id": None, "sample_round_id": None,
        "completion": None, "created_at": dt(-5, "10:00"), "origin": "source", "source_id": None, "rev": 1},
    "a_reinspect": {"id": "a_reinspect", "work_id": "w_meadow", "issue_id": "i_collar", "title": "Re-inspect reworked Lot 1 quantity (Vendor B)",
        "expected_outcome": "Re-inspection of the reworked quantity only, against the buyer-approved plan.",
        "assignee_id": "u_qa", "assignment_confirmed": True, "assigned_at": dt(-2, "10:00"), "due": d(2), "status": "open",
        "blocked": None, "requires_review": True, "requires_recheck_of": "ins_b_final1", "style_id": "s_meadow", "vendor_id": "v_lotus", "sample_round_id": None,
        "completion": None, "created_at": dt(-2, "10:00"), "origin": "source", "source_id": "src_meadow_email", "rev": 1},
    "a_defect_limits": {"id": "a_defect_limits", "work_id": "w_meadow", "issue_id": "i_collar", "title": "Confirm buyer-approved defect limits in writing",
        "expected_outcome": "Written confirmation of the applicable defect limits for the final-inspection plan.",
        "assignee_id": "u_merch1", "assignment_confirmed": True, "assigned_at": dt(-2, "11:00"), "due": d(1), "status": "open",
        "blocked": None, "requires_review": False, "style_id": "s_meadow", "vendor_id": None, "sample_round_id": None,
        "completion": None, "created_at": dt(-2, "11:00"), "origin": "source", "source_id": "src_meadow_reply", "rev": 1},
    "a_packing": {"id": "a_packing", "work_id": "w_meadow", "issue_id": "i_packing", "title": "Correct packing list for shipment 1",
        "expected_outcome": "Corrected packing list shared with warehouse.",
        "assignee_id": "u_prod", "assignment_confirmed": False, "assigned_at": None, "due": None, "status": "open",
        "blocked": None, "requires_review": False, "style_id": "s_meadow", "vendor_id": "v_sunrise", "sample_round_id": None,
        "completion": None, "created_at": dt(-1, "12:00"), "origin": "source", "source_id": None, "rev": 1},
    "a_price_list": {"id": "a_price_list", "work_id": "w_jaal", "issue_id": None, "title": "Prepare price list review pack for Jaal",
        "expected_outcome": "Review pack covering all 22 styles.", "assignee_id": "u_merch2", "assignment_confirmed": True,
        "assigned_at": dt(-5, "17:10"), "due": d(5), "status": "open", "blocked": None, "requires_review": False,
        "style_id": None, "vendor_id": None, "sample_round_id": None, "completion": None, "created_at": dt(-5, "17:10"),
        "origin": "source", "source_id": "src_jaal_note", "rev": 1},
    "a_lead_update": {"id": "a_lead_update", "work_id": "w_orbit", "issue_id": None, "title": "Send Argo Navis AW27 status summary to leadership",
        "expected_outcome": "One-page status for the AW27 development.", "assignee_id": "u_head", "assignment_confirmed": True,
        "assigned_at": dt(-3, "10:30"), "due": d(4), "status": "open", "blocked": None, "requires_review": False,
        "style_id": None, "vendor_id": None, "sample_round_id": None, "completion": None, "created_at": dt(-3, "10:30"),
        "origin": "source", "source_id": "src_weekly", "rev": 1},
    "a_vendor_review": {"id": "a_vendor_review", "work_id": None, "issue_id": None, "title": "Close the sleeve-hem finding at Sunrise Unit 2 (corrective action)",
        "expected_outcome": "Corrective evidence submitted for the sleeve-hem finding.", "assignee_id": "u_merch1", "assignment_confirmed": True,
        "assigned_at": dt(-14, "10:00"), "due": d(-2), "status": "open", "blocked": None, "requires_review": False,
        "style_id": None, "vendor_id": "v_sunrise", "sample_round_id": None, "finding_id": "f_sunrise_2", "completion": None,
        "created_at": dt(-14, "10:00"), "origin": "source", "source_id": None, "rev": 1},
    "a_no_date": {"id": "a_no_date", "work_id": "w_shirt", "issue_id": None, "title": "Add BOM for draft shirt style",
        "expected_outcome": "BOM added so the style can be marked sourcing-ready.", "assignee_id": "u_merch2", "assignment_confirmed": True,
        "assigned_at": dt(-6, "12:00"), "due": None, "status": "open", "blocked": None, "requires_review": False,
        "style_id": "s_vs3", "vendor_id": None, "sample_round_id": None, "completion": None, "created_at": dt(-6, "12:00"),
        "origin": "source", "source_id": None, "rev": 1},
    "a_head_overdue": {"id": "a_head_overdue", "work_id": "w_meadow", "issue_id": None, "title": "Decide escalation path for Vendor A PP correction",
        "expected_outcome": "Decide whether to hold Vendor A's allocation or move quantity to Vendor B.", "assignee_id": "u_head", "assignment_confirmed": True,
        "assigned_at": dt(-6, "10:00"), "due": d(-1), "status": "open", "blocked": None, "requires_review": False, "style_id": "s_meadow", "vendor_id": "v_sunrise",
        "sample_round_id": None, "completion": None, "created_at": dt(-6, "10:00"), "origin": "source", "source_id": None, "rev": 1},
    "a_head_today": {"id": "a_head_today", "work_id": "w_meadow", "issue_id": None, "title": "Confirm repeat-order intent with Argo Navis (verbal only so far)",
        "expected_outcome": "Written confirmation from the brand so the draft repeat order can be confirmed or dropped.", "assignee_id": "u_head", "assignment_confirmed": True,
        "assigned_at": dt(-3, "10:00"), "due": d(0), "status": "open", "blocked": None, "requires_review": False, "style_id": "s_meadow", "vendor_id": None,
        "sample_round_id": None, "completion": None, "created_at": dt(-3, "10:00"), "origin": "source", "source_id": "src_weekly", "rev": 1},
    "a_head_nodate": {"id": "a_head_nodate", "work_id": None, "issue_id": None, "title": "Shortlist resort-collar vendors for the SS28 capsule enquiry",
        "expected_outcome": "Short list with MOQ and limitations from the vendor directory.", "assignee_id": "u_head", "assignment_confirmed": True,
        "assigned_at": dt(-4, "12:30"), "due": None, "status": "open", "blocked": None, "requires_review": False, "style_id": None, "vendor_id": "v_kaveri",
        "sample_round_id": None, "completion": None, "created_at": dt(-4, "12:30"), "origin": "source", "source_id": "src_argo_enquiry", "rev": 1},
    "a_head_done": {"id": "a_head_done", "work_id": "w_orbit", "issue_id": None, "title": "Brief Kaveri on the Orbit sleeve pattern correction",
        "expected_outcome": "Vendor briefed with annotated photos.", "assignee_id": "u_head", "assignment_confirmed": True, "assigned_at": dt(-9, "10:00"), "due": d(-8),
        "status": "completed", "blocked": None, "requires_review": False, "style_id": "s_orbit", "vendor_id": "v_kaveri", "sample_round_id": None,
        "completion": {"by": "u_head", "at": dt(-8, "16:00"), "outcome": "Briefed on call with annotated photos (demo)."}, "created_at": dt(-9, "10:00"), "origin": "source", "source_id": None, "rev": 2},
    "a_done_example": {"id": "a_done_example", "work_id": "w_green", "issue_id": None, "title": "Send green set counter-sample to V-Mart",
        "expected_outcome": "Counter-sample couriered.", "assignee_id": "u_merch2", "assignment_confirmed": True,
        "assigned_at": dt(-12, "10:00"), "due": d(-7), "status": "completed", "blocked": None, "requires_review": False,
        "style_id": "s_gr1", "vendor_id": None, "sample_round_id": None,
        "completion": {"by": "u_merch2", "at": dt(-7, "15:00"), "outcome": "Couriered; tracking reference recorded (demo)."},
        "created_at": dt(-12, "10:00"), "origin": "source", "source_id": None, "rev": 2},
}

UPDATE_REQUESTS = {
    "r_sleeve": {"id": "r_sleeve", "action_id": "a_tech_review", "requester_id": "u_head", "recipient_id": "u_tech",
        "question": "Can you confirm whether the sleeve pitch on the corrected sample passes, or what else is needed before PP slot lock?",
        "requested_at": dt(-1, "17:00"), "response_due": d(1), "state": "awaiting", "response": None, "reminders": [],
        "requester_read_at": None, "leadership": False, "withdrawn": None},
    "r_lead": {"id": "r_lead", "action_id": "a_lead_update", "requester_id": "u_lead", "recipient_id": "u_head",
        "question": "Please send a short AW27 status including risks. I would like to review before the brand call.",
        "requested_at": dt(-1, "10:15"), "response_due": d(0), "state": "awaiting", "response": None, "reminders": [],
        "requester_read_at": None, "leadership": True, "withdrawn": None},
    "r_fabric": {"id": "r_fabric", "action_id": "a_fabric_options", "requester_id": "u_head", "recipient_id": "u_merch1",
        "question": "How far along is the fabric option deck?", "requested_at": dt(-1, "11:00"), "response_due": None,
        "state": "awaiting", "response": None, "reminders": [], "requester_read_at": None, "leadership": False, "withdrawn": None},
    "r_defect": {"id": "r_defect", "action_id": "a_defect_limits", "requester_id": "u_head", "recipient_id": "u_merch1",
        "question": "Have the buyer's defect limits been re-confirmed for the Lot 1 re-inspection?",
        "requested_at": dt(-1, "15:30"), "response_due": d(1), "state": "responded",
        "response": {"by": "u_merch1", "at": dt(0, "09:05"), "text": "Brand replied that limits are unchanged, but the written confirmation is still pending. Re-inspection can be scheduled; limits to be attached once received.",
                     "evidence": "Email from brand contact (summary supplied; original not available)"},
        "reminders": [], "requester_read_at": None, "leadership": False, "withdrawn": None},
}

COMMITMENTS = {
    "c_orbit_sample": {"id": "c_orbit_sample", "work_id": "w_orbit", "title": "Corrected sample (fit round 3) arrival", "sample_round_id": "sr_orbit_3", "kind": "Sample submission",
        "owner_id": "u_merch1", "original": d(-1), "planned": None, "agreed": d(-1), "proposed": d(3), "actual": None, "state": "proposed",
        "scope": "Style Orbit overshirt · fit round 3", "reason": "Vendor says re-dyed fabric lot arrives only tomorrow.",
        "proposer": "Kaveri Apparels (vendor)", "evidence_source_id": "src_orbit_email", "agreed_evidence": "Agreed 2 Oct in meeting (demo)",
        "readiness": "Technical review slot held for the day of arrival.", "style_id": "s_orbit", "rev": 1},
    "c_green_insp": {"id": "c_green_insp", "work_id": "w_green", "title": "Inspection planned", "kind": "Inspection", "owner_id": "u_merch2",
        "original": d(2), "planned": d(2), "agreed": None, "proposed": None, "actual": None, "state": "planned", "scope": "Green ethnic sets · pre-production",
        "reason": None, "proposer": None, "evidence_source_id": None, "agreed_evidence": None,
        "readiness": "Counter-sample receipt needs confirmation.", "style_id": "s_gr1", "rev": 1},
    "c_shirt_fabric": {"id": "c_shirt_fabric", "work_id": "w_shirt", "title": "Fabric options shared", "kind": "Brand deliverable", "owner_id": "u_merch1",
        "original": d(3), "planned": None, "agreed": d(3), "proposed": None, "actual": None, "state": "agreed", "scope": "New shirt development",
        "reason": None, "proposer": None, "evidence_source_id": None, "agreed_evidence": "Agreed with brand (demo)",
        "readiness": "Option deck in preparation.", "style_id": None, "rev": 1},
    "c_jaal_review": {"id": "c_jaal_review", "work_id": "w_jaal", "title": "Price list review with Jaal", "kind": "Brand meeting", "owner_id": "u_merch2",
        "original": d(6), "planned": None, "agreed": d(6), "proposed": None, "actual": None, "state": "agreed", "scope": "Core range · 22 styles",
        "reason": None, "proposer": None, "evidence_source_id": "src_jaal_note", "agreed_evidence": "Agreed with Jaal (demo)",
        "readiness": "Costing for all 22 styles complete; review pack pending.", "style_id": None, "rev": 1},
    "c_meadow_reinsp": {"id": "c_meadow_reinsp", "work_id": "w_meadow", "title": "Re-inspection of reworked Lot 1 (Vendor B)", "kind": "Inspection", "owner_id": "u_qa",
        "original": d(2), "planned": d(2), "agreed": d(2), "proposed": None, "actual": None, "state": "agreed", "scope": "Allocation Vendor B · Lot 1",
        "reason": None, "proposer": None, "evidence_source_id": "src_meadow_reply", "agreed_evidence": "Agreed with vendor (demo)",
        "readiness": "190 collars still in rework; reworked quantity only.", "style_id": "s_meadow", "rev": 1},
    "c_meadow_dispatch": {"id": "c_meadow_dispatch", "work_id": "w_meadow", "title": "Vendor A dispatch after PP correction", "kind": "Dispatch", "owner_id": "u_prod",
        "original": d(12), "planned": d(12), "agreed": d(12), "proposed": d(16), "actual": None, "state": "proposed", "scope": "Allocation Vendor A",
        "reason": "PP correction needs one more sample round.", "proposer": "Sunrise Garments (vendor)", "evidence_source_id": None,
        "agreed_evidence": "Original agreed date from PO (demo)", "readiness": "PP approval with comments pending.", "style_id": "s_meadow", "rev": 1},
}

WAITING = {
    "wt_kaveri": {"id": "wt_kaveri", "tracker_id": "u_merch1", "description": "Waiting for samples from vendor",
        "party": {"type": "vendor", "name": "Kaveri Apparels"}, "action_id": "a_resubmit", "work_id": "w_orbit",
        "expected": d(3), "latest": "Vendor proposed 9 Oct arrival (not agreed).", "state": "open", "update_received": False},
    "wt_review": {"id": "wt_review", "tracker_id": "u_head", "description": "Waiting for John Doe's review (Technical reviewer)",
        "party": {"type": "internal", "name": "John Doe · Technical reviewer"}, "action_id": "a_tech_review", "work_id": "w_orbit",
        "expected": d(-1), "latest": "Update requested yesterday.", "state": "open", "update_received": False},
    "wt_vmart": {"id": "wt_vmart", "tracker_id": "u_merch2", "description": "Waiting for brand approval",
        "party": {"type": "brand", "name": "V-Mart"}, "action_id": "a_confirm_counter", "work_id": "w_green",
        "expected": d(2), "latest": "Brand said they will confirm receipt and revert on colour by Thursday.", "state": "open", "update_received": False},
    "wt_defect": {"id": "wt_defect", "tracker_id": "u_head", "description": "Waiting for buyer-approved defect limits",
        "party": {"type": "brand", "name": "Argo Navis"}, "action_id": "a_defect_limits", "work_id": "w_meadow",
        "expected": d(1), "latest": "Brand says limits unchanged; written confirmation pending.", "state": "open", "update_received": False},
}

NOTES = {
    "n_private1": {"id": "n_private1", "author_id": "u_head", "title": "Kaveri call thoughts", "body": "Vendor sounded unsure on the 9 Oct date. Ask for the courier tracking tomorrow. Consider asking Lotus for a backup proto.",
        "visibility": "private", "links": {"brand_id": "b_argo", "work_id": "w_orbit"}, "event_date": d(-1), "created_at": dt(-1, "18:00"), "posted_at": None, "posted_to": []},
    "n_posted1": {"id": "n_posted1", "author_id": "u_head", "title": "Factory call: Lotus collar rework", "body": "Lotus confirmed rework on 410 of 600 collars is done; rest by 8 Oct. This is a statement from the vendor, not a changed commitment.",
        "visibility": "posted", "links": {"brand_id": "b_argo", "work_id": "w_meadow", "vendor_id": "v_lotus", "style_id": "s_meadow"}, "event_date": d(0), "created_at": dt(0, "09:20"),
        "posted_at": dt(0, "09:25"), "posted_to": ["w_meadow", "v_lotus", "s_meadow"]},
    "n_private2": {"id": "n_private2", "author_id": "u_merch2", "title": "V-Mart follow-up ideas", "body": "Ping buyer on Thursday morning if no receipt confirmation.",
        "visibility": "private", "links": {"brand_id": "b_vmart"}, "event_date": d(-1), "created_at": dt(-1, "13:00"), "posted_at": None, "posted_to": []},
}

COMMENTS = {
    "cm1": {"id": "cm1", "action_id": "a_tech_review", "author_id": "u_head", "ts": dt(-8, "10:00"), "text": "Left sleeve pitch looked ~1.5 cm forward in round 2. Photos are in the sample round."},
    "cm2": {"id": "cm2", "action_id": "a_tech_review", "author_id": "u_tech", "ts": dt(-7, "12:30"), "text": "Agreed. I will review the corrected piece as soon as it lands."},
}

EVENTS = [
    {"id": "e1", "ts": dt(-10, "11:30"), "actor_id": "u_head", "kind": "issue_opened", "title": "Issue opened: sleeve correction", "detail": "Left sleeve pitch 1.5 cm too forward on fit round 2.", "scope": {"brand_id": "b_argo", "work_id": "w_orbit", "style_id": "s_orbit", "issue_id": "i_sleeve", "vendor_id": "v_kaveri"}, "origin": "source", "source_id": "src_orbit_mtg"},
    {"id": "e2", "ts": dt(-10, "12:00"), "actor_id": "u_head", "kind": "assignment", "title": "Action assigned: get corrected sample", "detail": "Assigned to John Doe (Merchandiser, Argo Navis).", "scope": {"brand_id": "b_argo", "work_id": "w_orbit", "action_id": "a_resubmit", "issue_id": "i_sleeve"}, "origin": "source", "source_id": "src_orbit_mtg"},
    {"id": "e3", "ts": dt(-9, "09:00"), "actor_id": "u_head", "kind": "assignment", "title": "Review assigned: technical review of corrected sleeve", "detail": "Assigned to John Doe (Technical reviewer).", "scope": {"brand_id": "b_argo", "work_id": "w_orbit", "action_id": "a_tech_review", "issue_id": "i_sleeve"}, "origin": "source", "source_id": "src_orbit_mtg"},
    {"id": "e4", "ts": dt(-2, "10:00"), "actor_id": "u_merch1", "kind": "commitment_agreed", "title": "Corrected sample date agreed: due 5 Oct", "detail": "Original 5 Oct kept after vendor agreement.", "scope": {"brand_id": "b_argo", "work_id": "w_orbit", "style_id": "s_orbit"}, "origin": "source", "source_id": None},
    {"id": "e5", "ts": dt(-1, "16:20"), "actor_id": "u_merch1", "kind": "commitment_proposed", "title": "Vendor proposed revised arrival: 9 Oct (not agreed)", "detail": "Reason: re-dyed fabric lot arrives only tomorrow.", "scope": {"brand_id": "b_argo", "work_id": "w_orbit", "style_id": "s_orbit", "vendor_id": "v_kaveri"}, "origin": "source", "source_id": "src_orbit_email"},
    {"id": "e6", "ts": dt(-1, "17:00"), "actor_id": "u_head", "kind": "update_requested", "title": "Update requested · John Doe (Technical reviewer)", "detail": "Asked about sleeve review status.", "scope": {"brand_id": "b_argo", "work_id": "w_orbit", "action_id": "a_tech_review", "request_id": "r_sleeve"}, "origin": "source", "source_id": None},
    {"id": "e7", "ts": dt(-9, "10:00"), "actor_id": "u_head", "kind": "issue_opened", "title": "Issue opened: trim card mismatch on set 2", "detail": "", "scope": {"brand_id": "b_vmart", "work_id": "w_green", "issue_id": "i_trim", "style_id": "s_gr2"}, "origin": "source", "source_id": None},
    {"id": "e8", "ts": dt(-3, "15:00"), "actor_id": "u_head", "kind": "issue_resolved", "title": "Issue resolved: trim card mismatch on set 2", "detail": "Vendor replaced buttons; shade matched against approved trim card.", "scope": {"brand_id": "b_vmart", "work_id": "w_green", "issue_id": "i_trim", "style_id": "s_gr2"}, "origin": "source", "source_id": None},
    {"id": "e9", "ts": dt(-7, "15:00"), "actor_id": "u_merch2", "kind": "action_completed", "title": "Action completed: send green set counter-sample", "detail": "Couriered; tracking reference recorded (demo).", "scope": {"brand_id": "b_vmart", "work_id": "w_green", "action_id": "a_done_example", "style_id": "s_gr1"}, "origin": "source", "source_id": None},
    {"id": "e10", "ts": dt(-2, "14:05"), "actor_id": "u_merch2", "kind": "conversation", "title": "V-Mart said they will confirm receipt by Thursday", "detail": "Summary supplied; original message is not available.", "scope": {"brand_id": "b_vmart", "work_id": "w_green"}, "origin": "source", "source_id": "src_vmart_msg"},
    {"id": "e11", "ts": dt(-2, "09:45"), "actor_id": "u_qa", "kind": "inspection_failed", "title": "Lot 1 (Vendor B) failed final inspection", "detail": "Collar stitching: major defects above the recorded limit.", "scope": {"brand_id": "b_argo", "work_id": "w_meadow", "style_id": "s_meadow", "vendor_id": "v_lotus", "issue_id": "i_collar", "allocation_id": "al_b"}, "origin": "source", "source_id": "src_meadow_email"},
    {"id": "e12", "ts": dt(-1, "15:30"), "actor_id": "u_head", "kind": "update_requested", "title": "Update requested · John Doe (Merchandiser, Argo Navis)", "detail": "Asked whether defect limits were re-confirmed.", "scope": {"brand_id": "b_argo", "work_id": "w_meadow", "action_id": "a_defect_limits", "request_id": "r_defect"}, "origin": "source", "source_id": None},
    {"id": "e13", "ts": dt(0, "09:05"), "actor_id": "u_merch1", "kind": "response_received", "title": "Response received on defect-limit request", "detail": "Limits unchanged; written confirmation pending. The issue remains open.", "scope": {"brand_id": "b_argo", "work_id": "w_meadow", "action_id": "a_defect_limits", "request_id": "r_defect", "issue_id": "i_collar"}, "origin": "source", "source_id": None},
    {"id": "e14", "ts": dt(0, "08:55"), "actor_id": "u_prod", "kind": "conversation", "title": "Vendor B: rework 410/600 collars done", "detail": "Remaining 190 by 8 Oct (vendor statement).", "scope": {"brand_id": "b_argo", "work_id": "w_meadow", "style_id": "s_meadow", "vendor_id": "v_lotus"}, "origin": "source", "source_id": "src_meadow_reply"},
    {"id": "e15", "ts": dt(-3, "10:30"), "actor_id": "u_head", "kind": "meeting", "title": "Sourcing weekly review (multi-brand)", "detail": "Sections linked to Argo Navis, V-Mart and Jaal.", "scope": {"brand_id": "b_argo"}, "origin": "source", "source_id": "src_weekly"},
    {"id": "e16", "ts": dt(-3, "10:31"), "actor_id": "u_head", "kind": "meeting", "title": "Sourcing weekly review: V-Mart section", "detail": "Green sets counter-sample out; fabric options due next week.", "scope": {"brand_id": "b_vmart"}, "origin": "source", "source_id": "src_weekly"},
    {"id": "e17", "ts": dt(-3, "10:32"), "actor_id": "u_head", "kind": "meeting", "title": "Sourcing weekly review: Jaal section", "detail": "Costing complete; price list review 12 Oct.", "scope": {"brand_id": "b_jaal"}, "origin": "source", "source_id": "src_weekly"},
    {"id": "e18", "ts": dt(-4, "12:10"), "actor_id": "u_head", "kind": "conversation", "title": "Argo Navis: early enquiry on SS28 resort capsule", "detail": "Not linked to any work yet.", "scope": {"brand_id": "b_argo"}, "origin": "source", "source_id": "src_argo_enquiry"},
    {"id": "e19", "ts": dt(-5, "17:05"), "actor_id": "u_merch2", "kind": "document", "title": "Costing complete for 22 styles", "detail": "Core range v3 basis.", "scope": {"brand_id": "b_jaal", "work_id": "w_jaal"}, "origin": "source", "source_id": "src_jaal_note"},
    {"id": "e20", "ts": dt(0, "09:25"), "actor_id": "u_head", "kind": "note_posted", "title": "Update posted: Factory call – Lotus collar rework", "detail": "Posted to Meadow production, Lotus Knit Works and the Meadow shirt.", "scope": {"brand_id": "b_argo", "work_id": "w_meadow", "vendor_id": "v_lotus", "style_id": "s_meadow", "note_id": "n_posted1"}, "origin": "source", "source_id": None},
]

NOTIFICATIONS = [
    {"id": "nt1", "recipient_id": "u_tech", "ts": dt(-1, "17:00"), "kind": "update_requested", "text": "Update requested on: Technical review of corrected sleeve sample", "route": "/my-work?open=a_tech_review", "read_at": None, "demo": True},
    {"id": "nt2", "recipient_id": "u_head", "ts": dt(-1, "10:15"), "kind": "update_requested", "text": "Leadership requested an update on: Send Argo Navis AW27 status summary", "route": "/my-work?open=a_lead_update", "read_at": None, "demo": True},
    {"id": "nt3", "recipient_id": "u_head", "ts": dt(0, "09:05"), "kind": "response_received", "text": "New response on: Confirm buyer-approved defect limits in writing", "route": "/overview?work=w_meadow&action=a_defect_limits&request=r_defect", "read_at": None, "demo": True},
]
